from __future__ import annotations

from pathlib import Path
from typing import Any

from core.config import ensure_directories
from core.filesystem.sandbox import FileSandboxError
from core.filesystem.service import (
    delete_sandbox_file,
    list_sandbox_files,
    read_sandbox_file,
    write_sandbox_file,
)


def create_workspace_handler(parameters: dict[str, Any], context: dict[str, Any]) -> dict[str, Any]:
    _ = context
    name = parameters.get("name")
    if not isinstance(name, str) or not name.strip():
        raise ValueError("'name' is required")
    workspace_name = name.strip().replace("..", "").replace("/", "_")
    base_dir = ensure_directories().file_sandbox_dir / "workspaces"
    workspace_dir = base_dir / workspace_name
    workspace_dir.mkdir(parents=True, exist_ok=True)
    return {
        "workspace": workspace_name,
        "path": str(workspace_dir.relative_to(ensure_directories().file_sandbox_dir)),
    }


def generate_project_scaffold_handler(parameters: dict[str, Any], context: dict[str, Any]) -> dict[str, Any]:
    _ = context
    workspace = parameters.get("workspace")
    if not isinstance(workspace, str) or not workspace.strip():
        raise ValueError("'workspace' is required")

    base = ensure_directories().file_sandbox_dir / "workspaces" / workspace.strip()
    if not base.exists():
        raise ValueError("Workspace does not exist")

    files: dict[str, str] = {
        "README.md": f"# {workspace.strip()}\n\nGenerated by Victus files.generate_project_scaffold.\n",
        "src/main.py": (
            "def main() -> None:\n"
            "    print('hello from victus scaffold')\n"
            "\n\nif __name__ == '__main__':\n"
            "    main()\n"
        ),
        ".gitignore": "__pycache__/\n.venv/\n",
    }
    created: list[str] = []
    for rel_path, content in files.items():
        target = base / Path(rel_path)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        created.append(rel_path)

    return {"workspace": workspace.strip(), "created_files": created}


def list_files_handler(parameters: dict[str, Any], context: dict[str, Any]) -> dict[str, Any]:
    _ = parameters, context
    files = list_sandbox_files()
    return {"files": files, "count": len(files)}


def read_file_handler(parameters: dict[str, Any], context: dict[str, Any]) -> dict[str, Any]:
    _ = context
    path = parameters.get("path")
    if not isinstance(path, str) or not path.strip():
        raise ValueError("'path' is required")
    try:
        content = read_sandbox_file(path.strip())
    except FileSandboxError as exc:
        raise ValueError(str(exc)) from exc
    return {"path": path.strip(), "content": content, "size_bytes": len(content.encode())}


def write_file_handler(parameters: dict[str, Any], context: dict[str, Any]) -> dict[str, Any]:
    _ = context
    path = parameters.get("path")
    if not isinstance(path, str) or not path.strip():
        raise ValueError("'path' is required")
    content = str(parameters.get("content") or "")
    mode = str(parameters.get("mode") or "overwrite")
    if mode not in {"overwrite", "append"}:
        raise ValueError("mode must be 'overwrite' or 'append'")
    try:
        write_sandbox_file(path.strip(), content, mode)
    except FileSandboxError as exc:
        raise ValueError(str(exc)) from exc
    return {"ok": True, "path": path.strip()}


def delete_file_handler(parameters: dict[str, Any], context: dict[str, Any]) -> dict[str, Any]:
    _ = context
    path = parameters.get("path")
    if not isinstance(path, str) or not path.strip():
        raise ValueError("'path' is required")
    try:
        deleted = delete_sandbox_file(path.strip())
    except FileSandboxError as exc:
        raise ValueError(str(exc)) from exc
    return {"deleted": deleted, "path": path.strip()}
